chore: improve diagnosis during bootstrap
When starting Amaru, I forgot to setup a valid config directory
that is supposed to host the `snapshot.json` file, for instance.
The error message was not helping as it did not give my any
clue of which file was missing:

```
$> CONFIG_FOLDER=/unexisting_folder make bootstrap
Error: Os { code: 2, kind: NotFound, message: "No such file or directory" }
```

This change uses `thisError` to return more precise errors which
may help spot what the problem is faster, for instance:

```
$> CONFIG_FOLDER=/unexisting_folder make bootstrap
Error: ReadSnapshotsFile("/unexisting_folder/preprod/snapshots.json", Os { code: 2, kind: NotFound, message: "No such file or directory" })
```

This time I took care of not messing with the potential json output
of Amaru by simply propagating the error..

Signed-off-by: Pascal Grange <pascal@grange.nom.fr>